# Generated by Django 5.2 on 2025-04-30 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vardas')),
                ('last_name', models.CharField(max_length=100, verbose_name='Pavardė')),
                ('apartment_number', models.CharField(max_length=10, verbose_name='Buto numeris')),
                ('email', models.EmailField(max_length=254, verbose_name='El. paštas')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefono numeris')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gyventojas',
                'verbose_name_plural': 'Gyventojai',
            },
        ),
    ]
