# Generated by Django 5.2 on 2025-04-30 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Pavadinimas')),
                ('content', models.TextField(verbose_name='Pranešimo turinys')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo laikas')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sukūrė')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pranešimas',
                'verbose_name_plural': 'Pranešimai',
                'ordering': ['-created_at'],
            },
        ),
    ]
