# Generated by Django 5.2 on 2025-04-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
