# Generated by Django 5.2 on 2025-04-30 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resident_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('document_type', models.CharField(choices=[('contract', 'Nuomos sutartis'), ('invoice', 'Sąskaita'), ('other', 'Kitas dokumentas')], max_length=20, verbose_name='Dokumento tipas')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Failas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Įkėlimo data')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Aprašymas')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.resident')),
            ],
            options={
                'verbose_name': 'Dokumentas',
                'verbose_name_plural': 'Dokumentai',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
