# Generated by Django 5.2 on 2025-04-30 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Pavadinimas')),
                ('description', models.TextField(verbose_name='Aprašymas')),
                ('status', models.CharField(choices=[('past', 'Praeitas'), ('current', 'Dabartinis'), ('future', 'Ateities')], max_length=10, verbose_name='Statusas')),
                ('start_date', models.DateField(verbose_name='Pradžios data')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Pabaigos data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sukūrė')),
            ],
            options={
                'verbose_name': 'Remontas/Darbas',
                'verbose_name_plural': 'Remontai ir darbai',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maintenance/%Y/%m/%d/', verbose_name='Nuotrauka')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.maintenance')),
            ],
            options={
                'verbose_name': 'Remonto nuotrauka',
                'verbose_name_plural': 'Remonto nuotraukos',
            },
        ),
    ]
