# Generated by Django 5.2 on 2025-05-01 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_update_maintenance_statuses_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('past', 'Atliktas'), ('current', 'Dabartinis'), ('future', 'Ateities')], max_length=10, verbose_name='Statusas'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('for', 'Už'), ('against', 'Prieš')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.resident')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('resident',)},
            },
        ),
    ]
