# Generated by Django 5.2 on 2025-05-01 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_maintenance_status_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Pavadinimas')),
                ('description', models.TextField(verbose_name='Aprašymas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktyvus')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Pabaigos data')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sukūrė')),
            ],
            options={
                'verbose_name': 'Balsavimo tema',
                'verbose_name_plural': 'Balsavimo temos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.votingtopic'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('resident', 'topic')},
        ),
    ]
