# Generated by Django 5.2 on 2025-05-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_change_end_date_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingtopic',
            name='is_active',
        ),
        migrations.AddField(
            model_name='votingtopic',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Užbaigimo data'),
        ),
        migrations.AddField(
            model_name='votingtopic',
            name='status',
            field=models.CharField(choices=[('active', 'Aktyvus'), ('completed', 'Užbaigtas')], default='active', max_length=10, verbose_name='Būsena'),
        ),
    ]
