# Generated by Django 5.2 on 2025-05-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_complaint_model'),
        ('core', '0011_remove_votingtopic_is_active_and_more'),
    ]

    operations = [
    ]
