# Generated by Django 5.2 on 2025-05-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20250501_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='Telefono numeris'),
        ),
    ]
