# Generated by Django 5.2 on 2025-05-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chatmessage'),
        ('core', '0014_userprofile'),
    ]

    operations = [
    ]
