# Generated by Django 5.2 on 2025-05-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_0011_chatmessage_0014_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sistemos nustatymas',
                'verbose_name_plural': 'Sistemos nustatymai',
            },
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-start_date'], 'verbose_name': 'Remontas/darbas', 'verbose_name_plural': 'Remontai ir darbai'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Balsas', 'verbose_name_plural': 'Balsai'},
        ),
    ]
