# Generated by Django 5.2 on 2025-05-26 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_settings_alter_maintenance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelis')),
                ('object_id', models.CharField(max_length=50, verbose_name='Objekto ID')),
                ('action', models.CharField(choices=[('create', 'Sukūrimas'), ('update', 'Keitimas'), ('delete', 'Ištrynimas')], max_length=10, verbose_name='Veiksmas')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data ir laikas')),
                ('changes', models.TextField(blank=True, null=True, verbose_name='Pokyčiai')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas')),
            ],
            options={
                'verbose_name': 'Veiklos žurnalas',
                'verbose_name_plural': 'Veiklos žurnalas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
