# Generated by Django 5.2 on 2025-05-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Pavadinimas')),
                ('message', models.TextField(verbose_name='Pranešimo turinys')),
                ('alert_type', models.CharField(choices=[('info', 'Informacija'), ('warning', 'Įspėjimas'), ('error', 'Klaida'), ('security', 'Saugumas')], default='info', max_length=20, verbose_name='Tipas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo laikas')),
                ('is_read', models.BooleanField(default=False, verbose_name='Perskaityta')),
            ],
            options={
                'verbose_name': 'Sistemos įspėjimas',
                'verbose_name_plural': 'Sistemos įspėjimai',
                'ordering': ['-created_at'],
            },
        ),
    ]
