# Generated by Django 5.2 on 2025-05-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_systemalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Atsarginės kopijos',
                'verbose_name_plural': 'Atsarginės kopijos',
                'managed': False,
            },
        ),
    ]
