# Generated by Django 5.2 on 2025-05-28 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_systemadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemadmin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='systemadmin',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
